-- ============================================================
-- Boutique items + homepage guest feedbacks
-- Run in Supabase → SQL Editor
-- ============================================================

-- Boutique products (shown on /mall)
CREATE TABLE IF NOT EXISTS boutique_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL DEFAULT 'Boutique item',
    image_path TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Guest feedbacks / reviews (shown on homepage #review)
CREATE TABLE IF NOT EXISTS feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_name TEXT NOT NULL,
    message TEXT NOT NULL,
    rating NUMERIC(2, 1) NOT NULL DEFAULT 5.0 CHECK (rating >= 1 AND rating <= 5),
    photo_path TEXT DEFAULT '/images/about.jpg',
    is_published BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed boutique from existing static images (skip if already present)
INSERT INTO boutique_items (title, image_path) VALUES
('Boutique look 1', '/images/b01.jpg'),
('Boutique look 2', '/images/b1.jpg'),
('Boutique look 3', '/images/b2.jpg'),
('Boutique look 4', '/images/b03.jpg'),
('Boutique look 5', '/images/b3.jpg'),
('Boutique look 6', '/images/b4.jpg'),
('Boutique look 7', '/images/b5.jpg'),
('Boutique look 8', '/images/b6.jpg'),
('Boutique look 9', '/images/b7.jpg'),
('Boutique look 10', '/images/b8.jpg'),
('Boutique look 11', '/images/b9.jpg')
ON CONFLICT (image_path) DO NOTHING;

-- Seed starter feedbacks (only if table is empty)
INSERT INTO feedbacks (guest_name, message, rating, photo_path)
SELECT * FROM (VALUES
  (
    'Aaron Kigun',
    'If you are looking for a nice place to relax, look no further than Dikim Rock Garden. The combination of nature, VIP service, and standard security is unmatched.',
    4.5::numeric,
    '/images/about.jpg'
  ),
  (
    'Andrew Peter',
    'If you are looking for an intoxicating picnic spot or private club environment, check out Dikim Rock Garden. Beautiful lawns and amazing staff!',
    4.5::numeric,
    '/images/about.jpg'
  )
) AS seed(guest_name, message, rating, photo_path)
WHERE NOT EXISTS (SELECT 1 FROM feedbacks LIMIT 1);

-- RLS
ALTER TABLE boutique_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedbacks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read boutique" ON boutique_items;
CREATE POLICY "Allow public read boutique" ON boutique_items
  FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow admin insert boutique" ON boutique_items;
CREATE POLICY "Allow admin insert boutique" ON boutique_items
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin update boutique" ON boutique_items;
CREATE POLICY "Allow admin update boutique" ON boutique_items
  FOR UPDATE TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin delete boutique" ON boutique_items;
CREATE POLICY "Allow admin delete boutique" ON boutique_items
  FOR DELETE TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow public read published feedbacks" ON feedbacks;
CREATE POLICY "Allow public read published feedbacks" ON feedbacks
  FOR SELECT TO public USING (is_published = true);

DROP POLICY IF EXISTS "Allow admin read all feedbacks" ON feedbacks;
CREATE POLICY "Allow admin read all feedbacks" ON feedbacks
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin insert feedbacks" ON feedbacks;
CREATE POLICY "Allow admin insert feedbacks" ON feedbacks
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin update feedbacks" ON feedbacks;
CREATE POLICY "Allow admin update feedbacks" ON feedbacks
  FOR UPDATE TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow admin delete feedbacks" ON feedbacks;
CREATE POLICY "Allow admin delete feedbacks" ON feedbacks
  FOR DELETE TO authenticated USING (true);
