-- ============================================================
-- SUPABASE DATABASE SETUP SCRIPT FOR DIKIM ROCK GARDEN
-- Run this script inside the SQL Editor of your Supabase Dashboard
-- ============================================================

-- 1. Create Rooms Table
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    price NUMERIC(10, 2) NOT NULL,
    image_path TEXT NOT NULL,
    rating NUMERIC(2, 1) DEFAULT 4.5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Default Rooms matching index.php
INSERT INTO rooms (name, price, image_path, rating) VALUES
('Small Room', 10000.00, '/images/smallroom.jpg', 4.5),
('Family Room', 15000.00, '/images/familyroom.jpg', 4.5),
('Exclusive Suite', 20000.00, '/images/mediumroom.jpg', 4.5),
('Executive Suite', 25000.00, '/images/bigroom.jpg', 4.5),
('Executive Suite II', 30000.00, '/images/largeroom.jpg', 4.5)
ON CONFLICT (name) DO NOTHING;

-- 2. Create Gallery Table
CREATE TABLE IF NOT EXISTS gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_path TEXT NOT NULL UNIQUE,
    caption TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Default Gallery items matching index.php
INSERT INTO gallery (image_path, caption) VALUES
('/images/b02.jpg', 'Boutique display'),
('/images/fountain1.jpg', 'Garden fountain'),
('/images/g5.jpg', 'Garden view'),
('/images/g2.jpg', 'Garden scenery'),
('/images/fountain2.jpg', 'Fountain'),
('/images/b04.jpg', 'Boutique items'),
('/images/t2.jpg', 'Dining area'),
('/images/sideview.jpg', 'Side view')
ON CONFLICT (image_path) DO NOTHING;

-- 3. Create Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    room TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    reference TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    arrival_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- If transactions already exists without arrival_date, run:
-- ALTER TABLE transactions ADD COLUMN IF NOT EXISTS arrival_date DATE;

-- 4. Create Contact Messages Table
CREATE TABLE IF NOT EXISTS contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT DEFAULT '',
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- ROW LEVEL SECURITY (RLS) POLICIES & CONFIGURE STORAGE BUCKETS
-- ============================================================
-- By default, new Supabase tables might have RLS active. 
-- To ensure the frontend and admin dashboard can access the data, 
-- you can run the following commands or enable them via the dashboard:

-- 1. Enable RLS on all tables
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- 2. Create public access policies for Rooms and Gallery
CREATE POLICY "Allow public read access to rooms" ON rooms FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read access to gallery" ON gallery FOR SELECT TO public USING (true);

-- 3. Create admin modify policies for Rooms and Gallery (authenticated users only)
CREATE POLICY "Allow admin to insert rooms" ON rooms FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow admin to update rooms" ON rooms FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow admin to delete rooms" ON rooms FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow admin to insert gallery items" ON gallery FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow admin to delete gallery items" ON gallery FOR DELETE TO authenticated USING (true);

-- 4. Create public insert policy for Transactions and Contact Messages
CREATE POLICY "Allow public to record bookings" ON transactions FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public to submit inquiries" ON contact_messages FOR INSERT TO public WITH CHECK (true);

-- 5. Create admin read policy for Transactions and Contact Messages
CREATE POLICY "Allow admin to view transactions" ON transactions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin to view inquiries" ON contact_messages FOR SELECT TO authenticated USING (true);

-- ============================================================
-- SUPABASE STORAGE CONFIGURATION
-- ============================================================
-- 1. Go to the "Storage" section in your Supabase Dashboard.
-- 2. Create a new Storage Bucket called: "dikim-images"
-- 3. Set the bucket privacy level to "Public" (crucial so image URLs are accessible).
-- 4. In the Bucket's "Policies" tab, add a policy that:
--    * Allows "authenticated" users to UPLOAD, UPDATE, and DELETE files.
--    * Allows "public" users to READ files.
